name: Auto-run Jupyter Notebook
on: [push]

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install opencv-python-headless numpy pandas scikit-learn jupyter nbconvert matplotlib scipy

      - name: Install System Dependencies
        run: sudo apt-get update && sudo apt-get install -y libgl1 libglib2.0-dev libgtk2.0-dev pkg-config

      - name: Run Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute distance_classification.ipynb --output executed_notebook.ipynb

      - name: Upload Output Image
        uses: actions/upload-artifact@v3
        with:
          name: output-image
          path: output.png
